---

- name: Create cloudflare ddns config directory
  ansible.builtin.file:
    path: "{{ cloudflare_ddns_conf_dir }}"
    state: directory
    owner: "{{ cloudflare_ddns_user }}"
    group: "{{ cloudflare_ddns_group }}"
    mode: '0755'

- name: Create cloudflare ddns config file
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ cloudflare_ddns_conf_dir }}/config.json"
    owner: "{{ cloudflare_ddns_user }}"
    group: "{{ cloudflare_ddns_group }}"
    mode: '0644'
